services:
  - type: web
    name: webtaixiu
    env: node
    plan: free
    buildCommand: rm -rf node_modules package-lock.json && npm install && npm run build
    startCommand: npm start
    autoDeploy: true
