services:
  - type: web
    name: webtaixiu
    env: node
    plan: free
    buildCommand: npm install --production=false && chmod +x ./node_modules/.bin/vite && npm run build
    startCommand: npm run start
    autoDeploy: true
